name: Create release

on:
  workflow_run:
    branches: [ master ]
    workflows: [ build ]

jobs:
  latest-release:
    runs-on: ubuntu-latest

    steps:
    - name: Download zip file
      uses: actions/download-artifact@v2
      with:
        name: zip

    - name: Release latest dev build
      if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
      uses: marvinpinto/action-automatic-releases@v1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: 'latest'
        prerelease: true
        files: |
          *.zip

    - name: Prepare draft release of tag
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      uses: marvinpinto/action-automatic-releases@v1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        draft: true
        prerelease: false
        files: |
          *.zip
